name: Mirror to Gitee

on:
  push:             # run every time you push anything to GitHub
    branches: [ master ]     # or whatever your canonical branch is
  workflow_dispatch:       # plus a manual “Run workflow” button

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v1.5
      with:
        src: github/SamuelGong      # where the code comes from
        dst: gitee/openeuler        # where it goes
        dst_token:  ${{ secrets.GITEE_TOKEN }}    # or dst_key for SSH
        force_update: true                        # overwrite if histories diverge
        debug: true                               # verbose logs (optional)
        lfs: true 
        static_list: "hey"
